server:
  port: 8080
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/Users/victorcerkasov/Documents/Food_Delivery-master/D:/Food_Delivery/DataBase/users
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
  main:
    allow-circular-references: true